---
name: go
on: [push, pull_request]
jobs:
  lint: # <- name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go mod tidy
      - uses: golangci/golangci-lint-action@v7

  test-unit: # <- name
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod
    - run: go mod tidy
    - run: go test -v ./...
